Repository OpenSILEX/phis-webapp, pull requests merged in 2018-10, with the labels that each got.

#72 Small translations corrects for the view of the experiments
  translations/fr/app.php
  views/experiment/view.php
Labels: minor bug

#69 FIX BUG-VM-3 Hide add document button on projects for guests
  views/project/view.php
Labels: minor bug

#73 Fix BUG when uploading dataset
  controllers/DatasetController.php
Labels: P0, major bug

#58 Fix project creation issues
  controllers/ProjectController.php
  models/yiiModels/YiiProjectModel.php
Labels: P0, major bug

#75 fix agronomical objects data visualisation
  views/layer/view.php
Labels: major bug

#74 Radiometric Target IHM
  composer.lock
  config/params.php
  controllers/DocumentController.php
  controllers/InfrastructureController.php
  controllers/RadiometricTargetController.php
  models/wsModels/WSRadiometricTargetModel.php
  models/yiiModels/RadiometricTargetSearch.php
  models/yiiModels/YiiModelsConstants.php
  models/yiiModels/YiiRadiometricTargetModel.php
  translations/fr/app.php
  translations/fr/yii.php
  views/layouts/main.php
  views/radiometric-target/_form.php
  views/radiometric-target/create.php
  views/radiometric-target/index.php
  views/radiometric-target/update.php
  views/radiometric-target/view.php
  web/documents/DatasetFiles/datasetTemplate.csv
Labels: new feature

#76 Minor changes on infrastructures
  config/i18n.php
  config/web.php
  models/yiiModels/YiiInfrastructureModel.php
  translations/fr/app.php
  views/infrastructure/index.php
  views/infrastructure/view.php
  views/layouts/main.php
Labels: improve user experience
