Repository OpenSILEX/phis-webapp, pull requests merged in 2018-09, with the labels that each got.

#50 correction typo on _form_characterize.php : focal length in mm (not nm)
  translations/fr/app.php
  translations/fr/messages.php
  translations/fr/yii.php
  views/project/_form.php
  views/sensor/_form-characterize.php
Labels: good first issue

#51 Sensors - characterize : inputs types with decimal when needed and fix bug 44
  views/sensor/_form-characterize.php
Labels: major bug

#57 Fix#102
  models/yiiModels/YiiInstanceDefinitionModel.php
Labels: P1, minor bug

#55 Generation of acquisition session excel file from the web interface
  components/helpers/SiteMessages.php
  composer.json
  config/params.php
  controllers/AcquisitionSessionMetadataFileController.php
  models/wsModels/WSAcquisitionSession.php
  models/yiiModels/YiiDocumentModel.php
  translations/fr/app.php
  translations/fr/messages.php
  views/layouts/main.php
  views/site/warning.php
Labels: P0, new feature

#61 Fix acquisition session issue
  controllers/AcquisitionSessionMetadataFileController.php
Labels: P1, major bug

#62 updates for the new release (v.2.6)
  components/helpers/SiteMessages.php
  composer.json
  views/layouts/main.php
Labels: P0, enhancement

#65 Fix bugs v2.6
  composer.json
  models/yiiModels/YiiVectorModel.php
Labels: P0, major bug

#67 add version numbers instead of @dev in composer.json
  composer.json
Labels: P0, major bug
