Repository OpenSILEX/phis-webapp, pull requests merged in 2018-11, with the labels that each got.

#85 fix paginations
  models/wsModels/WSActiveRecord.php
  models/yiiModels/UserSearch.php
  models/yiiModels/YiiAgronomicalObjectModel.php
  models/yiiModels/YiiAnnotationModel.php
  models/yiiModels/YiiConcernModel.php
  models/yiiModels/YiiDocumentModel.php
  models/yiiModels/YiiExperimentModel.php
  models/yiiModels/YiiFileInformationModel.php
  models/yiiModels/YiiGroupModel.php
  models/yiiModels/YiiInfrastructureModel.php
  models/yiiModels/YiiInstanceDefinitionModel.php
  models/yiiModels/YiiProjectModel.php
  models/yiiModels/YiiRadiometricTargetModel.php
  models/yiiModels/YiiSensorModel.php
  models/yiiModels/YiiUserModel.php
  models/yiiModels/YiiVectorModel.php
Labels: major bug

#86 change update button access and add add document button
  views/radiometric-target/view.php
Labels: minor bug

#77 sensors properties from key moved in the yiiSensorModel
  controllers/SensorController.php
  models/yiiModels/YiiSensorModel.php
Labels: refactoring

#88 fix users indew view
  models/yiiModels/UserSearch.php
Labels: P0, major bug

#89 increase documents size to 40Mo
  views/document/_form.php
Labels: minor bug

#90 Fix bug in case of multiple sensor variables graphs (only one was shown)
  views/sensor/_view_sensor_graph.php
Labels: minor bug
