Repository OpenSILEX/phis-webapp, pull requests merged in 2018-12, with the labels that each got.

#93 Update doc link
  views/layouts/main.php
Labels: enhancement

#94 hide the link to download the acquisition session file for 4P
  views/layouts/main.php
Labels: enhancement

#99 fix variable label generation
  views/variable/_form.php
Labels: minor bug

#95 Add ajax login form to handle token expiration and allow user to reconnect without loosing data or get an error
  assets/AppAsset.php
  composer.json
  composer.lock
  controllers/SiteController.php
  models/wsModels/WSConstants.php
  models/wsModels/WSTokenModel.php
  translations/fr/messages.php
  views/layouts/main.php
  web/css/site.css
Labels: enhancement, minor bug

#96 Fix paginations (and in the dropdownlists) + fix variable index search
  controllers/AgronomicalObjectController.php
  controllers/AnnotationController.php
  controllers/DatasetController.php
  controllers/DocumentController.php
  controllers/ExperimentController.php
  controllers/GroupController.php
  controllers/InfrastructureController.php
  controllers/ProjectController.php
  controllers/RadiometricTargetController.php
  controllers/SensorController.php
  controllers/UserController.php
  controllers/VariableController.php
  controllers/VectorController.php
  models/wsModels/WSActiveRecord.php
  models/yiiModels/UserSearch.php
  models/yiiModels/YiiInstanceDefinitionModel.php
  models/yiiModels/YiiUserModel.php
  translations/fr/app.php
  views/variable/index.php
Labels: major bug, refactoring
