Repository OpenSILEX/phis-webapp, pull requests merged in 2019-01, with the labels that each got.

#103 Species index
  controllers/SpeciesController.php
  models/wsModels/WSSpeciesModel.php
  models/yiiModels/SpeciesSearch.php
  models/yiiModels/YiiSpeciesModel.php
  views/layouts/main.php
  views/site/ontology.php
  views/species/index.php
Labels: new feature

#104 Hide filters which does not work
  views/agronomical-object/index.php
  views/document/index.php
  views/experiment/index.php
  views/group/index.php
  views/infrastructure/index.php
  views/project/index.php
  views/radiometric-target/index.php
  views/sensor/index.php
  views/user/index.php
  views/vector/index.php
Labels: minor bug

#100 Fix bug when no environment data are found for a sensor
  views/sensor/_view_sensor_graph.php
Labels: minor bug

#102 Instances link widget
  components/widgets/LinkObjectsWidget.php
  controllers/ExperimentController.php
  controllers/SensorController.php
  models/wsModels/WSExperimentModel.php
  models/yiiModels/YiiExperimentModel.php
  models/yiiModels/YiiSensorModel.php
  views/experiment/view.php
  views/sensor/view.php
Labels: new feature

#107 Scientific objects link doc and rename
  controllers/DatasetController.php
  controllers/ExperimentController.php
  controllers/ScientificObjectController.php
  models/wsModels/WSScientificObjectModel.php
  models/yiiModels/GroupSearch.php
  models/yiiModels/ScientificObjectSearch.php
  models/yiiModels/UnitSearch.php
  models/yiiModels/YiiExperimentModel.php
  models/yiiModels/YiiMethodModel.php
  models/yiiModels/YiiScientificObjectModel.php
  views/layouts/main.php
  views/scientific-object/_form.php
  views/scientific-object/create.php
  views/scientific-object/index.php
Labels: enhancement, refactoring

#112 Fix bug user creation
  controllers/UserController.php
Labels: P2

#114 Fix vocabulary page - remove species
  controllers/ScientificObjectController.php
  views/site/ontology.php
Labels: P1, major bug

#109 Fix scientific objects
  controllers/ScientificObjectController.php
  models/yiiModels/YiiScientificObjectModel.php
  views/layer/view.php
  views/scientific-object/_form.php
Labels: minor bug

#111 Fix bug to display correctly annotations with specials characters
  components/widgets/AnnotationGridViewWidget.php
  views/annotation/index.php
  views/annotation/view.php
Labels: minor bug

#108 Refactor sensor profile characterzation
  controllers/SensorController.php
  models/yiiModels/SensorDataSearch.php
  translations/fr/app.php
  translations/fr/messages.php
  views/sensor/_form-characterize.php
  views/sensor/characterize.php
  views/sensor/index.php
  views/sensor/view.php
Labels: improve user experience

#110 Move generate map button from experiment to layer view
  views/experiment/view.php
  views/layer/view.php
Labels: improve user experience

#124 Fix layers
  views/layer/view.php
Labels: refactoring

#126 change webapp title
  views/site/index.php
Labels: minor bug
