Repository OpenSILEX/phis-webapp, pull requests merged in 2019-07, with the labels that each got.

#225 Fix bug on date/time selection for events
  config/params.php
  views/event/_form.php
Labels: P3, improve user experience, minor bug

#226 Optimization of the scientific objects download
  controllers/ScientificObjectController.php
Labels: improve user experience, minor bug

#229 Projects triplestore
  config/params.php
  controllers/ProjectController.php
  controllers/ScientificObjectController.php
  models/yiiModels/ProjectSearch.php
  models/yiiModels/YiiExperimentModel.php
  models/yiiModels/YiiProjectModel.php
  translations/fr/app.php
  views/event/_form.php
  views/experiment/view.php
  views/project/_form.php
  views/project/index.php
  views/project/view.php
Labels: enhancement
