Repository OpenSILEX/phis-webapp, pull requests merged in 2019-06, with the labels that each got.

#167 Add R web application linking with OpenCPU server
  composer.json
  composer.lock
  config/config.php
  config/params.php
  controllers/DataAnalysisController.php
  models/yiiModels/DataAnalysisAppSearch.php
  translations/fr/messages.php
  views/data-analysis/iframe-view.php
  views/data-analysis/index.php
  views/layouts/main.php
  web/images/logos/R_logo.png
Labels: new feature

#218 Optimizations
  controllers/VariableController.php
  models/wsModels/WSActiveRecord.php
  models/yiiModels/VariableSearch.php
  models/yiiModels/YiiInstanceDefinitionModel.php
  models/yiiModels/YiiSensorModel.php
Labels: P1, enhancement

#220 Scientificobjects creation add labels
  controllers/ScientificObjectController.php
  models/yiiModels/YiiSpeciesModel.php
  views/scientific-object/_form.php
  views/scientific-object/_form_update.php
Labels: minor bug

#223 devices fix required fields
  models/yiiModels/YiiActuatorModel.php
  models/yiiModels/YiiSensorModel.php
Labels: minor bug
