Repository OpenSILEX/phis-webapp, pull requests merged in 2019-03, with the labels that each got.

#152 fix bug scientific object creation
  controllers/ScientificObjectController.php
Labels: major bug

#153 Add baseUri param
  config/params.php
Labels: major bug

#160 Update web_services.php urls
  config/web_services.php
Labels: minor bug

#163 cleans for training
  views/layouts/main.php
  web/documents/AOFiles/exportedData/.gitignore
Labels: minor bug

#164 Return to origin url after annotation creation
  components/widgets/AnnotationButtonWidget.php
  controllers/AnnotationController.php
  models/yiiModels/YiiAnnotationModel.php
  views/annotation/_form.php
Labels: enhancement, improve user experience

#165 Return to origin url after event creation
  components/widgets/EventButtonWidget.php
  controllers/EventController.php
  models/yiiModels/EventPost.php
  views/event/_form.php
Labels: enhancement, improve user experience

#166 Return to origin url after document creation
  controllers/DocumentController.php
  models/yiiModels/YiiDocumentModel.php
  views/document/_form.php
  views/experiment/view.php
  views/infrastructure/view.php
  views/project/view.php
  views/radiometric-target/view.php
  views/sensor/view.php
  views/vector/view.php
Labels: enhancement, improve user experience, minor bug
