Repository OpenSILEX/phis-webapp, pull requests merged in 2019-04, with the labels that each got.

#168 Variable creation - check if trait, method and unit are filled before send the form
  translations/fr/app.php
  views/variable/_form.php
Labels: major bug

#172 Change error reporting level (Remove error page on warning)
  web/index.php
Labels: improve user experience

#174 fix experiments list and species list
  controllers/ScientificObjectController.php
  models/wsModels/WSExperimentModel.php
  models/yiiModels/YiiExperimentModel.php
  models/yiiModels/YiiSpeciesModel.php
  views/layouts/main.php
Labels: minor bug

#175 fix users pagination get for create and update groups
  controllers/GroupController.php
Labels: minor bug

#169 Update sensor
  controllers/SensorController.php
  models/yiiModels/YiiSensorModel.php
  translations/fr/app.php
  views/sensor/_form-update.php
  views/sensor/update.php
  views/sensor/view.php
Labels: new feature

#171 Sensors add model
  controllers/SensorController.php
  models/yiiModels/SensorSearch.php
  models/yiiModels/YiiSensorModel.php
  translations/fr/app.php
  views/sensor/_form-update.php
  views/sensor/_form.php
  views/sensor/index.php
  views/sensor/view.php
Labels: new feature

#179 View experiment : title alias instead of uri
  views/experiment/view.php
Labels: minor bug

#176 Scientific objects index : fix incomplete experiments list
  controllers/ScientificObjectController.php
  models/yiiModels/YiiExperimentModel.php
Labels: minor bug

#173 Scientific objects update
  controllers/ScientificObjectController.php
  models/wsModels/WSScientificObjectModel.php
  models/yiiModels/YiiScientificObjectModel.php
  translations/fr/messages.php
  views/experiment/view.php
  views/scientific-object/_form_update.php
  views/scientific-object/index.php
  views/scientific-object/update.php
Labels: new feature

#182 fix merge
  models/yiiModels/ActuatorSearch.php
  views/actuator/view.php
Labels: major bug

#183 fix vector update pagination
  controllers/VectorController.php
Labels: major bug

#184 Actuators : fix data visualization
  views/actuator/_view_actuator_graph.php
Labels: major bug

#185 Map visualization - title : label instead of the uri
  controllers/LayerController.php
  views/experiment/view.php
  views/layer/view.php
Labels: minor bug
