Repository OpenSILEX/phis-webapp, pull requests merged in 2019-05, with the labels that each got.

#188 Add annotation and event creation link for scientific objects
  components/widgets/AnnotationButtonWidget.php
  components/widgets/EventButtonWidget.php
  views/scientific-object/index.php
Labels: improve user experience, new feature

#187 fix sensor data view
  models/yiiModels/DeviceDataSearch.php
Labels: major bug

#192 Experiments - map visualization : fix date format on data visualization
  views/data/_form_data_graph.php
Labels: minor bug

#186 Map Visualization : fix breadcrumbs
  views/layer/view.php
Labels: minor bug

#189 Sensors index fixes
  controllers/SensorController.php
  models/yiiModels/SensorSearch.php
  translations/fr/messages.php
  views/sensor/index.php
Labels: enhancement

#190 Actuators index fixes
  controllers/ActuatorController.php
  models/yiiModels/ActuatorSearch.php
  views/actuator/index.php
Labels: enhancement

#191 Vectors index fixes
  controllers/VectorController.php
  models/yiiModels/VectorSearch.php
  views/vector/index.php
Labels: enhancement

#193 Fix carriage return when multiple body values in annotations
  components/widgets/AnnotationGridViewWidget.php
  views/annotation/view.php
Labels: minor bug

#194 Add geomerty to Sientific Object export
  composer.json
  composer.lock
  controllers/ScientificObjectController.php
Labels: enhancement, improve user experience

#195 fix annotation creation date bug
  models/yiiModels/YiiAnnotationModel.php
Labels: P2, minor bug

#197 Enable annotation index menu
  controllers/AnnotationController.php
  models/yiiModels/AnnotationSearch.php
  models/yiiModels/YiiUserModel.php
  translations/fr/app.php
  views/annotation/index.php
  views/layouts/main.php
Labels: P2, improve user experience

#196 upgrade to v3.2
  views/layouts/main.php
Labels: enhancement

#198 Events modification interface with multiple concerned items
  components/widgets/ConcernedItemGridViewWidget.php
  components/widgets/PropertyWidget.php
  components/widgets/PropertyWidgetWithActions.php
  components/widgets/PropertyWidgetWithoutActions.php
  components/widgets/concernedItem/ConcernedItemGridViewWidget.php
  components/widgets/event/EventButtonWidget.php
  components/widgets/event/EventGridViewWidget.php
  components/widgets/handsontableInput/HandsontableInputWidget.php
  components/widgets/handsontableInput/HandsontableInputWidgetAsset.php
  components/widgets/handsontableInput/assets/css/handsontable-input-widget.css
  components/widgets/handsontableInput/assets/js/handsontable-input-widget.js
  components/widgets/handsontableInput/views/_handsontable-input.php
  composer.json
  composer.lock
  controllers/ActuatorController.php
  controllers/EventController.php
  controllers/ExperimentController.php
  controllers/GenericController.php
  controllers/InfrastructureController.php
  controllers/ProjectController.php
  controllers/RadiometricTargetController.php
  controllers/SensorController.php
  controllers/VectorController.php
  models/yiiModels/EventAction.php
  models/yiiModels/EventCreation.php
  models/yiiModels/EventPost.php
  models/yiiModels/EventSearch.php
  models/yiiModels/EventUpdate.php
  models/yiiModels/YiiConcernedItemModel.php
  models/yiiModels/YiiEventModel.php
  translations/en/app.php
  translations/fr/app.php
  translations/fr/messages.php
  views/actuator/view.php
  views/event/_form.php
  views/event/create.php
  views/event/index.php
  views/event/update.php
  views/event/view.php
  views/experiment/view.php
  views/infrastructure/view.php
  views/project/view.php
  views/radiometric-target/_form.php
  views/radiometric-target/view.php
  views/scientific-object/index.php
  views/sensor/view.php
  views/variable/create.php
  views/vector/view.php
  web/css/site.css
Labels: new feature

#177 Refactoring dataset
  components/widgets/event/EventButtonWidget.php
  config/params.php
  controllers/DatasetController.php
  controllers/DocumentController.php
  models/wsModels/WSProvenanceModel.php
  models/wsModels/WSUriModel.php
  models/yiiModels/YiiDatasetModel.php
  translations/fr/app.php
  translations/fr/messages.php
  views/dataset/_form.php
  views/dataset/_form_dataset_created.php
  views/dataset/create.php
  views/layer/view.php
  views/layouts/main.php
  web/documents/DatasetFiles/datasetExemple.csv
Labels: enhancement, improve user experience

#200 Fix bad Widget class import
  views/actuator/index.php
  views/sensor/index.php
  views/vector/index.php
Labels: major bug

#201 fix error redirection to project view after creation
  controllers/ProjectController.php
Labels: minor bug

#204 fix spaces between infrastructure view buttons
  views/infrastructure/view.php
Labels: minor bug

#202 fix characterization of already characterized sensor
  views/sensor/view.php
Labels: minor bug

#203 Display labels for Project and experiment concerned by events and fix bad link for vector edition
  views/event/index.php
  views/vector/index.php
  web/css/site.css
Labels: minor bug

#206 fix experiment sensor link
  components/widgets/LinkObjectsWidget.php
  views/experiment/view.php
Labels: minor bug

#207 Fix unused date parameter for graph visualization
  views/actuator/_form_actuator_graph.php
  views/sensor/_form_sensor_graph.php
Labels: P2, improve user experience, minor bug

#209 fix document redirection to actuator
  controllers/DocumentController.php
Labels: minor bug

#211 Scientific Object index search
  models/yiiModels/ScientificObjectSearch.php
  models/yiiModels/YiiScientificObjectModel.php
  views/scientific-object/index.php
Labels: enhancement, minor bug

#213 Footer improved with links to website, twitter and github accounts ; contact menu added
  config/config.php
  config/params.php
  config/web_services.php
  controllers/SiteController.php
  translations/fr/app.php
  translations/fr/messages.php
  views/layouts/main.php
  views/site/contact.php
  views/site/index.php
Labels: enhancement

#215 fix scientific object creation
  controllers/ScientificObjectController.php
Labels: P0, major bug

#214 Data visualization of a scientific object for a selected variable
  controllers/ScientificObjectController.php
  models/yiiModels/YiiExperimentModel.php
  views/data/_form_data_graph.php
  views/scientific-object/data_visualization.php
  views/scientific-object/index.php
Labels: new feature
